//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInStation
    {
        public int studentInStationId { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public int statioId { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public int studentId { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Student Student { get; set; }
    }
}
